name: labfinal
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  outline_material_icons: ^0.1.1
  flutter_image_slideshow: any
  rflutter_alert: ^1.0.2
  font_awesome_flutter: ^8.4.0
  intl_phone_field: ^2.1.0
  flutter_otp_text_field: ^1.0.0
  geolocator: ^7.7.1
  geocoding: ^2.0.1
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.0
  firebase_database: any
  image_picker: any
  path_provider: any
  flutter_launcher_icons: ^0.9.2
  firebase_storage: ^10.2.4
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "images/img.png"
  adaptive_icon_forground: "images/img.png"


flutter:

  uses-material-design: true

  assets:
    - images/

#  fonts:
#    - family: Poppins
#      fonts:
#        - asset: fonts/Poppins-Regular.ttf
#        - asset: fonts/Poppins-Bold.ttf
